create table public.audit_table (
  log_id uuid not null,
  user_id uuid null,
  action_type text null,
  details jsonb null,
  timestamp timestamp with time zone null default now(),
  timestamp_local timestamp without time zone null,
  constraint audit_table_pkey primary key (log_id),
  constraint FK_audit_table_user_id foreign KEY (user_id) references user_table (user_id)
) TABLESPACE pg_default;

create table public.claim_table (
  claim_id uuid not null,
  item_id uuid null,
  claimer_name text null,
  claimer_school_email text null,
  claimer_contact_num text null,
  processed_by_staff_id uuid null,
  claimed_at timestamp with time zone null default now(),
  constraint claim_table_pkey primary key (claim_id),
  constraint ux_claim_item_claimid unique (item_id, claim_id),
  constraint FK_claim_table_item_id foreign KEY (item_id) references item_table (item_id),
  constraint FK_claim_table_processed_by_staff_id foreign KEY (processed_by_staff_id) references user_table (user_id)
) 

create table public.fraud_reports_table (
  report_id uuid not null default gen_random_uuid (),
  post_id integer not null,
  report_status public.fraud_report_status_enum not null default 'under_review'::fraud_report_status_enum,
  reason_for_reporting text null,
  date_reported timestamp with time zone not null default now(),
  proof_image_url text null,
  reported_by uuid null,
  processed_by_staff_id uuid null,
  claimer_name text null,
  claimer_school_email text null,
  claimer_contact_num text null,
  claimed_at timestamp with time zone null,
  claim_processed_by_staff_id uuid null,
  claim_id uuid null,
  constraint fraud_reports_table_pkey primary key (report_id),
  constraint fk_fraud_reports_claim_staff foreign KEY (claim_processed_by_staff_id) references user_table (user_id),
  constraint fk_fraud_reports_post foreign KEY (post_id) references post_table (post_id) on delete CASCADE,
  constraint fraud_reports_table_processed_by_staff_id_fkey foreign KEY (processed_by_staff_id) references user_table (user_id),
  constraint fraud_reports_table_reported_by_fkey foreign KEY (reported_by) references user_table (user_id)
)
create table public.global_announcements_table (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  sent_by uuid null,
  scheduled_on timestamp with time zone null,
  message text null,
  failed_user_ids jsonb null,
  description text null,
  image_id bigint null,
  constraint global_announcements_table_pkey primary key (id),
  constraint global_announcements_table_image_id_fkey foreign KEY (image_id) references notification_image_table (image_id),
  constraint global_announcements_table_sent_by_fkey foreign KEY (sent_by) references user_table (user_id)
)
create table public.item_image_table (
  item_image_id serial not null,
  image_hash text null,
  image_link text null,
  created_at timestamp with time zone null default now(),
  constraint item_image_table_pkey primary key (item_image_id)
)
create table public.item_table (
  item_id uuid not null default gen_random_uuid (),
  item_name text null,
  item_description text null,
  image_id integer null,
  status public.item_status_enum null default 'unclaimed'::item_status_enum,
  type public.item_type_enum null,
  created_at timestamp with time zone null default now(),
  category text null,
  item_metadata jsonb null,
  search_vector tsvector GENERATED ALWAYS as ()
  returned_at_local timestamp without time zone null,
  constraint item_table_pkey primary key (item_id),
  constraint FK_item_table_image_id foreign KEY (image_id) references item_image_table (item_image_id)
)
create table public.location_lookup (
  location_id serial not null,
  parent_location_id integer null,
  location_name text null,
  full_location_name text null,
  location_level public.location_level_enum null,
  constraint location_lookup_pkey primary key (location_id),
  constraint FK_location_lookup_parent_location_id foreign KEY (parent_location_id) references location_lookup (location_id)
)

create table public.notification_image_table (
  image_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  image_url text null,
  constraint notification_image_table_pkey primary key (image_id)
)

create table public.notification_table (
  notification_id uuid not null,
  created_at timestamp with time zone null default now(),
  description text null,
  sent_to uuid null,
  sent_by uuid null,
  is_read boolean null default false,
  type text null,
  data jsonb null,
  image_id bigint null,
  global_announcement_id bigint null,
  title text null,
  constraint notification_table_pkey primary key (notification_id),
  constraint FK_notification_table_sent_by foreign KEY (sent_by) references user_table (user_id),
  constraint FK_notification_table_sent_to foreign KEY (sent_to) references user_table (user_id),
  constraint notification_table_global_announcement_id_fkey foreign KEY (global_announcement_id) references global_announcements_table (id),
  constraint notification_table_image_id_fkey foreign KEY (image_id) references notification_image_table (image_id)
)

create table public.pending_match (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  post_id integer null,
  poster_id uuid null,
  status text null,
  is_retriable boolean null,
  failed_reason text null,
  constraint pending_match_pkey primary key (id),
  constraint pending_match_post_id_fkey foreign KEY (post_id) references post_table (post_id),
  constraint pending_match_poster_id_fkey foreign KEY (poster_id) references user_table (user_id)
)

create table public.post_table (
  post_id serial not null,
  poster_id uuid null,
  status public.post_status_enum null default 'pending'::post_status_enum,
  item_id uuid null,
  accepted_by_staff_id uuid null,
  submitted_on_date_id integer null,
  last_seen_date_id integer null,
  last_seen_time_id integer null,
  last_seen_location_id integer null,
  is_anonymous boolean not null default false,
  submitted_on_date timestamp with time zone not null default now(),
  submitted_on_date_local timestamp without time zone not null,
  accepted_on_date timestamp with time zone null default now(),
  accepted_on_date_local timestamp without time zone null,
  rejection_reason text null,
  constraint post_table_pkey primary key (post_id),
  constraint ux_post_unique_combination unique (
    poster_id,
    item_id,
    last_seen_time_id,
    last_seen_location_id,
    is_anonymous
  ),
  constraint FK_post_table_last_seen_date_id foreign KEY (last_seen_date_id) references date_lookup (date_id),
  constraint FK_post_table_last_seen_location_id foreign KEY (last_seen_location_id) references location_lookup (location_id),
  constraint FK_post_table_accepted_by_staff_id foreign KEY (accepted_by_staff_id) references user_table (user_id),
  constraint FK_post_table_poster_id foreign KEY (poster_id) references user_table (user_id),
  constraint FK_post_table_last_seen_time_id foreign KEY (last_seen_time_id) references time_lookup (time_id),
  constraint FK_post_table_item_id foreign KEY (item_id) references item_table (item_id)
)

create table public.search_rate_limit (
  user_id uuid not null,
  search_count integer null default 0,
  window_start timestamp with time zone null default now(),
  constraint search_rate_limit_pkey primary key (user_id)
)

create table public.time_lookup (
  time_id serial not null,
  hours integer null,
  minutes integer null,
  constraint time_lookup_pkey primary key (time_id)
)

create table public.user_table (
  user_id uuid not null,
  user_name text null,
  email text null,
  profile_picture_url text null,
  user_type public.user_type_enum null default 'User'::user_type_enum,
  created_at timestamp with time zone null default now(),
  last_login timestamp with time zone null,
  notification_token text null,
  global_announcement_id bigint null,
  constraint user_table_pkey primary key (user_id),
  constraint user_table_global_announcement_id_fkey foreign KEY (global_announcement_id) references global_announcements_table (id)
)